### ISSUE TITLE
Security vuln

### ISSUE THREAD

**Issue by ColdSauce** [maxwofford/simple-upload#1]
Heyo! Sorry for snooping, but I was curious! 

I think there's a security vuln here! 

https://github.com/maxwofford/simple-upload/blob/main/server.js#L29

if the file name is `../../.ssh/authorized_keys` (basically they can use `..` to go to any directory on the file system, and they can overwrite any file on the server.

**Comment by maxwofford** [comment]
Thanks for flagging this! Wasn't up for long, but I'm checking logs now to see if anything was accessed. I think this was addressed in https://github.com/maxwofford/simple-upload/commit/87de3ae2dc03edcde9c28066126a7bb8fc5ac58c.

**Comment by ColdSauce** [comment]
Nice! Yeah I think that should resolve it :)
